name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - uses: actions/setup-node@v1
      name: Setup Node
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Build
      run: yarn install && yarn build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: zip -r stremio-web.zip ./build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: stremio-web.zip
        asset_name: stremio-web.zip
        tag: ${{ github.ref }}
        overwrite: true
    - run: |
        curl -H "Content-Type: application/zip" \
             -H "Authorization: Bearer ${{ secrets.netlify_access_token }}" \
             --data-binary "@stremio-web.zip" \
             https://api.netlify.com/api/v1/sites/stremio-staging.netlify.com/deploys
    
